### ISSUE TITLE
How to generate the replay-related files?

### ISSUE THREAD

**Issue by Sobbbbbber** [cityflow-project/data#4]
When I used the cityflow with another dataset, how can I generate the _roadnetLogFile_ and _replayLogFile_ to replay the traffic process?

Thanks a lot!

@only-changer @zhc134 @soodoshll @Hzfengsy

**Comment by zhc134** [comment]
roadnetLogFile and replayLogFile are generated by CityFlow, which are specified in the config file, check https://cityflow.readthedocs.io/en/latest/start.html

If you want to generate input road network and flow, please check https://github.com/cityflow-project/CityFlow/tree/master/tools/generator or generate them according to the correct format [road network](https://cityflow.readthedocs.io/en/latest/roadnet.html), [flow](https://cityflow.readthedocs.io/en/latest/flow.html)
